name: Update readme with blog posts
# on: 
#   schedule:
#     # Once a day at 8 AM
#     - cron: 0 8 * * *
on:
  push:
    branches: [ master ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://dev.to/susmitadey
          readme-section: feed
          max: 10 # max number of items (default 5)
          template: "#### [{{ title }}]({{ link }}) \n*{{ contentSnippet }}*\n\n"
